//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSNWebMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Platform { get; set; }
        public string ImageString { get; set; }
        public string Difficulty { get; set; }
        public string DifficultyPoints { get; set; }
        public string Completed { get; set; }
        public string Owned { get; set; }
        public string RarityPoints { get; set; }
        public string Link { get; set; }
    }
}
